<Project>
  <PropertyGroup>
    <SanBuildVersion Condition="'$(SanBuildVersion)' == ''">0.6.0</SanBuildVersion>
    <SanAssemblyVersion Condition="'$(SanAssemblyVersion)' == ''">0.6.0.0</SanAssemblyVersion>
    <Version>$(SanBuildVersion)</Version>
    <FileVersion>$(SanAssemblyVersion)</FileVersion>
    <AssemblyVersion>$(SanAssemblyVersion)</AssemblyVersion>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <InformationalVersion Condition="'$(SourceRevisionId)' == ''">$(SanBuildVersion)</InformationalVersion>
    <InformationalVersion Condition="'$(SourceRevisionId)' != ''">$(SanBuildVersion)+$(SourceRevisionId)</InformationalVersion>
  </PropertyGroup>
</Project>
